chore: finish searchable dropdown
malaysianpaygap/website pull request #16
Opened 2022-04-10 07:16 UTC by nicolehuey

2022-04-10 08:11 UTC, Ganthology commented
<img width="1162" alt="Screenshot 2022-04-10 at 4 10 00 PM" src="https://user-images.githubusercontent.com/18641991/162608995-30b0c854-9ba4-42a3-81e9-d10ee03de4d8.png">
@nicolehuey it's showing 2 field?

2022-04-12 07:24 UTC, Ganthology approved these changes
Have checked the preview url, I think should be good to go. 
What do you think, @malcolm-kee

2022-04-12 07:49 UTC, malcolm-kee commented
1. I was thinking a separate `SearchableDropdown` component instead of overwriting `Dropdown`, so that we can supports both use case (searchable or not).
1. Focus style is not consistent with text field, not only there is a border, the color is also not updated based on status (success/warning)
1. When there is no search result, it should displays a "No result" text instead of a white box.
1. Incorrect behavior for keyboard users, which I believe downshift should already be handling them if you use it correctly:
   - When I focus the component via pressing tab from previous element, the options does not appear.
   - When the options is shown and I press Escape, it is not closed.

Also, please add `resolves #3` in the description of this PR so merging this would auto close the issue.

@nicolehuey if you need help to resolves them, let me know. We can schedule a pair program session using LiveShare.

2022-04-12 07:52 UTC, malcolm-kee requested changes

2022-04-12 07:52 UTC, malcolm-kee commented on src/components/form/dropdown.tsx
> +    const [open, setOpen] = React.useState(false);
don't track the open state yourself, let downshift manage it. You should able to get `isOpen` state from the children callback

2022-04-13 10:55 UTC, nicolehuey commented on src/components/form/dropdown.tsx
> +            {...getRootProps(undefined, { suppressRefError: true })}
i get this warning but couldn't find way to fix it.
`downshift: You must apply the ref prop "ref" from getRootProps onto your root element`

2022-04-13 11:01 UTC, nicolehuey commented on src/components/form/dropdown.tsx
> +    const [open, setOpen] = React.useState(false);
Initially I used downshift's isOpen state but it doesn't support opening of dropdown when onclick on input box unless with another arrow button. I wrestled with that for a while then end up just using my own state.  Or perhaps I missed something hmm

2022-04-13 11:18 UTC, malcolm-kee commented on src/components/form/dropdown.tsx
> +            {...getRootProps(undefined, { suppressRefError: true })}
Try 
```jsx
<div  {...getRootProps({ ref: forwardedRef })} >
```

2022-04-13 11:24 UTC, malcolm-kee commented on src/components/form/dropdown.tsx
> +    const [open, setOpen] = React.useState(false);
Try call `openMenu` available in the children callback (see [here](https://github.com/downshift-js/downshift#actions)) for input onFocus, so something like

```jsx
<DownShift>
  {({ getInputProps, openMenu }) => (
    <input {...getInputProps({
      onFocus: openMenu
    })} />
  )}
</DownShift>
```

2022-04-13 11:27 UTC, nicolehuey commented on src/components/form/dropdown.tsx
> +            {...getRootProps(undefined, { suppressRefError: true })}
<img width="1037" alt="Screen Shot 2022-04-13 at 7 26 51 pm" src="https://user-images.githubusercontent.com/41655015/163170385-2a7ea20a-d767-413e-b4b6-f5200ecd6c3f.png">

2022-04-13 11:31 UTC, malcolm-kee commented on src/components/form/dropdown.tsx
> +            {...getRootProps(undefined, { suppressRefError: true })}
I think the type is incorrect, try 

```
<div  {...getRootProps({ ref: forwardedRef as any })} >
```

2022-04-18 13:24 UTC, nicolehuey commented on src/components/form/dropdown.tsx
> +            {...getRootProps(undefined, { suppressRefError: true })}
still has warning error :( 
`next-dev.js?a3a8:32 Warning: div: `ref` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop.`

2022-04-19 11:30 UTC, Ganthology commented
Have checked the preview link and provide feedback to @nicolehuey, the styling is consistent for both browsers except when in Safari the focus ring is in dark purple colour.
The suggestions 1, 3, 4 by Malcolm are implemented, but for 2 I'm not sure.

2022-04-19 16:09 UTC, malcolm-kee commented
@nicolehuey I've pushed some changes are should be good to go now.

## What I changed:

- Change the forwardRef generic from `HTMLSelectElement` to `HTMLInputElemtn` and forward to to the `input` element instead of the root div.
- Remove `getRootProps`. I apologise as my previous comment was wrong due to my confusion on how Downshift component works. If we returns a single div in the children callback, there is no need to manually call `getRootProps`.
- Make `id` props required for `SearchableDropdown`. This is required for `Downshift` component to be SSR friendly, see https://github.com/downshift-js/downshift/issues/602
- Style the highlighted option based on `highlightedIndex`, so that when user use keyboard Up/Down arrow to move the option, the highlighted option is visually visible.
- Make the color of "No result" lighter to differentiate with valid option.

2022-04-19 16:09 UTC, malcolm-kee commented on src/components/form/dropdown.tsx
> +            {...getRootProps(undefined, { suppressRefError: true })}
This is not needed. I misunderstand how `getRootProps` should be used.

2022-04-20 01:23 UTC, merged